// This file is auto-generated by @hey-api/openapi-ts

/**
 * AgentConfigCreate
 * 创建Agent配置的请求模型
 */
export type AgentConfigCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Agent Type
     */
    agent_type: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
};

/**
 * AgentConfigPublic
 * 返回给客户端的Agent配置模型
 */
export type AgentConfigPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Agent Type
     */
    agent_type: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Owner Id
     */
    owner_id: string;
};

/**
 * AgentConfigsPublic
 * Agent配置列表响应
 */
export type AgentConfigsPublic = {
    /**
     * Data
     */
    data: Array<AgentConfigPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_files-upload_file
 */
export type BodyFilesUploadFile = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * FilePublic
 */
export type FilePublic = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Original Filename
     */
    original_filename: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * File Size
     */
    file_size: number;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * FilesPublic
 */
export type FilesPublic = {
    /**
     * Data
     */
    data: Array<FilePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PDCACycleCreate
 * 创建PDCA循环的请求模型
 */
export type PdcaCycleCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Phase
     */
    phase?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Agent Type
     */
    agent_type?: string | null;
    /**
     * Agent Config Id
     */
    agent_config_id?: string | null;
    /**
     * Goal
     */
    goal: string;
    /**
     * Plan Details
     */
    plan_details?: {
        [key: string]: unknown;
    };
    /**
     * Agent Input
     */
    agent_input?: {
        [key: string]: unknown;
    };
};

/**
 * PDCACyclePublic
 * 返回给客户端的PDCA循环模型
 */
export type PdcaCyclePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Phase
     */
    phase?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * State Data
     */
    state_data?: {
        [key: string]: unknown;
    };
    /**
     * Agent Type
     */
    agent_type?: string | null;
    /**
     * Agent Config Id
     */
    agent_config_id?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Completed At
     */
    completed_at?: string | null;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Owner Id
     */
    owner_id: string;
};

/**
 * PDCACyclesPublic
 * PDCA循环列表响应
 */
export type PdcaCyclesPublic = {
    /**
     * Data
     */
    data: Array<PdcaCyclePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type ItemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type ItemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemsError = ItemsReadItemsErrors[keyof ItemsReadItemsErrors];

export type ItemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type ItemsReadItemsResponse = ItemsReadItemsResponses[keyof ItemsReadItemsResponses];

export type ItemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type ItemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsCreateItemError = ItemsCreateItemErrors[keyof ItemsCreateItemErrors];

export type ItemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsCreateItemResponse = ItemsCreateItemResponses[keyof ItemsCreateItemResponses];

export type ItemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsDeleteItemError = ItemsDeleteItemErrors[keyof ItemsDeleteItemErrors];

export type ItemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ItemsDeleteItemResponse = ItemsDeleteItemResponses[keyof ItemsDeleteItemResponses];

export type ItemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors];

export type ItemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsReadItemResponse = ItemsReadItemResponses[keyof ItemsReadItemResponses];

export type ItemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsUpdateItemError = ItemsUpdateItemErrors[keyof ItemsUpdateItemErrors];

export type ItemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsUpdateItemResponse = ItemsUpdateItemResponses[keyof ItemsUpdateItemResponses];

export type FilesReadFilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/files/';
};

export type FilesReadFilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilesReadFilesError = FilesReadFilesErrors[keyof FilesReadFilesErrors];

export type FilesReadFilesResponses = {
    /**
     * Successful Response
     */
    200: FilesPublic;
};

export type FilesReadFilesResponse = FilesReadFilesResponses[keyof FilesReadFilesResponses];

export type FilesDeleteFileEndpointData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/files/{id}';
};

export type FilesDeleteFileEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilesDeleteFileEndpointError = FilesDeleteFileEndpointErrors[keyof FilesDeleteFileEndpointErrors];

export type FilesDeleteFileEndpointResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type FilesDeleteFileEndpointResponse = FilesDeleteFileEndpointResponses[keyof FilesDeleteFileEndpointResponses];

export type FilesReadFileData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/files/{id}';
};

export type FilesReadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilesReadFileError = FilesReadFileErrors[keyof FilesReadFileErrors];

export type FilesReadFileResponses = {
    /**
     * Successful Response
     */
    200: FilePublic;
};

export type FilesReadFileResponse = FilesReadFileResponses[keyof FilesReadFileResponses];

export type FilesUploadFileData = {
    body: BodyFilesUploadFile;
    path?: never;
    query?: never;
    url: '/api/v1/files/upload';
};

export type FilesUploadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilesUploadFileError = FilesUploadFileErrors[keyof FilesUploadFileErrors];

export type FilesUploadFileResponses = {
    /**
     * Successful Response
     */
    200: FilePublic;
};

export type FilesUploadFileResponse = FilesUploadFileResponses[keyof FilesUploadFileResponses];

export type FilesDownloadFileData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/files/{id}/download';
};

export type FilesDownloadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilesDownloadFileError = FilesDownloadFileErrors[keyof FilesDownloadFileErrors];

export type FilesDownloadFileResponses = {
    /**
     * Response Files-Download File
     * Successful Response
     */
    200: unknown;
};

export type FilesGetFileUrlData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Expires In
         */
        expires_in?: number;
    };
    url: '/api/v1/files/{id}/url';
};

export type FilesGetFileUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilesGetFileUrlError = FilesGetFileUrlErrors[keyof FilesGetFileUrlErrors];

export type FilesGetFileUrlResponses = {
    /**
     * Response Files-Get File Url
     * Successful Response
     */
    200: unknown;
};

export type PdcaReadCyclesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Parent Id
         */
        parent_id?: string | null;
        /**
         * Phase
         */
        phase?: string | null;
        /**
         * Status Param
         */
        status_param?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/pdca/cycles';
};

export type PdcaReadCyclesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PdcaReadCyclesError = PdcaReadCyclesErrors[keyof PdcaReadCyclesErrors];

export type PdcaReadCyclesResponses = {
    /**
     * Successful Response
     */
    200: PdcaCyclesPublic;
};

export type PdcaReadCyclesResponse = PdcaReadCyclesResponses[keyof PdcaReadCyclesResponses];

export type PdcaCreateCycleData = {
    body: PdcaCycleCreate;
    path?: never;
    query?: never;
    url: '/api/v1/pdca/cycles';
};

export type PdcaCreateCycleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PdcaCreateCycleError = PdcaCreateCycleErrors[keyof PdcaCreateCycleErrors];

export type PdcaCreateCycleResponses = {
    /**
     * Successful Response
     */
    201: PdcaCyclePublic;
};

export type PdcaCreateCycleResponse = PdcaCreateCycleResponses[keyof PdcaCreateCycleResponses];

export type PdcaDeleteCycleData = {
    body?: never;
    path: {
        /**
         * Cycle Id
         */
        cycle_id: string;
    };
    query?: never;
    url: '/api/v1/pdca/cycles/{cycle_id}';
};

export type PdcaDeleteCycleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PdcaDeleteCycleError = PdcaDeleteCycleErrors[keyof PdcaDeleteCycleErrors];

export type PdcaDeleteCycleResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type PdcaDeleteCycleResponse = PdcaDeleteCycleResponses[keyof PdcaDeleteCycleResponses];

export type PdcaReadCycleData = {
    body?: never;
    path: {
        /**
         * Cycle Id
         */
        cycle_id: string;
    };
    query?: never;
    url: '/api/v1/pdca/cycles/{cycle_id}';
};

export type PdcaReadCycleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PdcaReadCycleError = PdcaReadCycleErrors[keyof PdcaReadCycleErrors];

export type PdcaReadCycleResponses = {
    /**
     * Successful Response
     */
    200: PdcaCyclePublic;
};

export type PdcaReadCycleResponse = PdcaReadCycleResponses[keyof PdcaReadCycleResponses];

export type PdcaExecuteCycleData = {
    body?: never;
    path: {
        /**
         * Cycle Id
         */
        cycle_id: string;
    };
    query?: never;
    url: '/api/v1/pdca/cycles/{cycle_id}/execute';
};

export type PdcaExecuteCycleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PdcaExecuteCycleError = PdcaExecuteCycleErrors[keyof PdcaExecuteCycleErrors];

export type PdcaExecuteCycleResponses = {
    /**
     * Successful Response
     */
    200: PdcaCyclePublic;
};

export type PdcaExecuteCycleResponse = PdcaExecuteCycleResponses[keyof PdcaExecuteCycleResponses];

export type PdcaReadChildCyclesData = {
    body?: never;
    path: {
        /**
         * Cycle Id
         */
        cycle_id: string;
    };
    query?: never;
    url: '/api/v1/pdca/cycles/{cycle_id}/children';
};

export type PdcaReadChildCyclesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PdcaReadChildCyclesError = PdcaReadChildCyclesErrors[keyof PdcaReadChildCyclesErrors];

export type PdcaReadChildCyclesResponses = {
    /**
     * Successful Response
     */
    200: PdcaCyclesPublic;
};

export type PdcaReadChildCyclesResponse = PdcaReadChildCyclesResponses[keyof PdcaReadChildCyclesResponses];

export type PdcaReadAgentConfigsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Agent Type
         */
        agent_type?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/pdca/agents/configs';
};

export type PdcaReadAgentConfigsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PdcaReadAgentConfigsError = PdcaReadAgentConfigsErrors[keyof PdcaReadAgentConfigsErrors];

export type PdcaReadAgentConfigsResponses = {
    /**
     * Successful Response
     */
    200: AgentConfigsPublic;
};

export type PdcaReadAgentConfigsResponse = PdcaReadAgentConfigsResponses[keyof PdcaReadAgentConfigsResponses];

export type PdcaCreateAgentConfigRouteData = {
    body: AgentConfigCreate;
    path?: never;
    query?: never;
    url: '/api/v1/pdca/agents/configs';
};

export type PdcaCreateAgentConfigRouteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PdcaCreateAgentConfigRouteError = PdcaCreateAgentConfigRouteErrors[keyof PdcaCreateAgentConfigRouteErrors];

export type PdcaCreateAgentConfigRouteResponses = {
    /**
     * Successful Response
     */
    201: AgentConfigPublic;
};

export type PdcaCreateAgentConfigRouteResponse = PdcaCreateAgentConfigRouteResponses[keyof PdcaCreateAgentConfigRouteResponses];

export type PdcaListAgentTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/pdca/agents/types';
};

export type PdcaListAgentTypesResponses = {
    /**
     * Response Pdca-List Agent Types
     * Successful Response
     */
    200: {
        [key: string]: Array<string>;
    };
};

export type PdcaListAgentTypesResponse = PdcaListAgentTypesResponses[keyof PdcaListAgentTypesResponses];

export type PrivateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors];

export type PrivateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses];

export type ClientOptions = {
    baseUrl: `${string}://frontend` | (string & {});
};