"""Add PDCA models

Revision ID: 2b3273e81533
Revises: 83832351eb7e
Create Date: 2026-04-06 13:00:08.721370

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2b3273e81533'
down_revision = '83832351eb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_config',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_config_name'), 'agent_config', ['name'], unique=False)
    op.create_table('pdca_cycle',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('state_data', sa.JSON(), nullable=True),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('agent_config_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['pdca_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdca_cycle_name'), 'pdca_cycle', ['name'], unique=False)
    op.create_table('execution_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['pdca_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_log_cycle_id'), 'execution_log', ['cycle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_log_cycle_id'), table_name='execution_log')
    op.drop_table('execution_log')
    op.drop_index(op.f('ix_pdca_cycle_name'), table_name='pdca_cycle')
    op.drop_table('pdca_cycle')
    op.drop_index(op.f('ix_agent_config_name'), table_name='agent_config')
    op.drop_table('agent_config')
    # ### end Alembic commands ###
