/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWebTestsRouteImport } from './routes/_layout/web-tests'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPdcaRouteImport } from './routes/_layout/pdca'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutFilesRouteImport } from './routes/_layout/files'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutWebTestsTestIdRouteImport } from './routes/_layout/web-tests.$testId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWebTestsRoute = LayoutWebTestsRouteImport.update({
  id: '/web-tests',
  path: '/web-tests',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPdcaRoute = LayoutPdcaRouteImport.update({
  id: '/pdca',
  path: '/pdca',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFilesRoute = LayoutFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWebTestsTestIdRoute = LayoutWebTestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => LayoutWebTestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/files': typeof LayoutFilesRoute
  '/items': typeof LayoutItemsRoute
  '/pdca': typeof LayoutPdcaRoute
  '/settings': typeof LayoutSettingsRoute
  '/web-tests': typeof LayoutWebTestsRouteWithChildren
  '/web-tests/$testId': typeof LayoutWebTestsTestIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/files': typeof LayoutFilesRoute
  '/items': typeof LayoutItemsRoute
  '/pdca': typeof LayoutPdcaRoute
  '/settings': typeof LayoutSettingsRoute
  '/web-tests': typeof LayoutWebTestsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/web-tests/$testId': typeof LayoutWebTestsTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/files': typeof LayoutFilesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/pdca': typeof LayoutPdcaRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/web-tests': typeof LayoutWebTestsRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/web-tests/$testId': typeof LayoutWebTestsTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/files'
    | '/items'
    | '/pdca'
    | '/settings'
    | '/web-tests'
    | '/web-tests/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/files'
    | '/items'
    | '/pdca'
    | '/settings'
    | '/web-tests'
    | '/'
    | '/web-tests/$testId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/files'
    | '/_layout/items'
    | '/_layout/pdca'
    | '/_layout/settings'
    | '/_layout/web-tests'
    | '/_layout/'
    | '/_layout/web-tests/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/web-tests': {
      id: '/_layout/web-tests'
      path: '/web-tests'
      fullPath: '/web-tests'
      preLoaderRoute: typeof LayoutWebTestsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pdca': {
      id: '/_layout/pdca'
      path: '/pdca'
      fullPath: '/pdca'
      preLoaderRoute: typeof LayoutPdcaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/files': {
      id: '/_layout/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof LayoutFilesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/web-tests/$testId': {
      id: '/_layout/web-tests/$testId'
      path: '/$testId'
      fullPath: '/web-tests/$testId'
      preLoaderRoute: typeof LayoutWebTestsTestIdRouteImport
      parentRoute: typeof LayoutWebTestsRoute
    }
  }
}

interface LayoutWebTestsRouteChildren {
  LayoutWebTestsTestIdRoute: typeof LayoutWebTestsTestIdRoute
}

const LayoutWebTestsRouteChildren: LayoutWebTestsRouteChildren = {
  LayoutWebTestsTestIdRoute: LayoutWebTestsTestIdRoute,
}

const LayoutWebTestsRouteWithChildren = LayoutWebTestsRoute._addFileChildren(
  LayoutWebTestsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutFilesRoute: typeof LayoutFilesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutPdcaRoute: typeof LayoutPdcaRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutWebTestsRoute: typeof LayoutWebTestsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutFilesRoute: LayoutFilesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutPdcaRoute: LayoutPdcaRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutWebTestsRoute: LayoutWebTestsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
